# Generated by Django 4.2.29 on 2026-03-25 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Outlet Category',
                'verbose_name_plural': 'Outlet Categories',
                'db_table': 'outlets_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='outlet name')),
                ('address', models.TextField(verbose_name='address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='contact person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('operating_notes', models.TextField(blank=True, verbose_name='operating notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_outlets', to=settings.AUTH_USER_MODEL, verbose_name='assigned manager')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlets', to='outlets.outletcategory', verbose_name='category')),
                ('outlet_manager_user', models.OneToOneField(blank=True, limit_choices_to={'role': 'outlet_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_outlet', to=settings.AUTH_USER_MODEL, verbose_name='outlet manager user')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'db_table': 'outlets_outlet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_type', models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('violation', 'Violation'), ('notice', 'Notice')], max_length=20, verbose_name='notice type')),
                ('reason', models.TextField(verbose_name='reason')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount (if applicable)')),
                ('source', models.CharField(help_text='Original source system or reference', max_length=255, verbose_name='source')),
                ('issued_date', models.DateField(verbose_name='issued date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='legacy_notices/%Y/%m/%d/', verbose_name='attachment')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_notices', to='outlets.outlet', verbose_name='outlet')),
            ],
            options={
                'verbose_name': 'Legacy Notice',
                'verbose_name_plural': 'Legacy Notices',
                'db_table': 'outlets_legacy_notice',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['name'], name='outlets_out_name_c74212_idx'),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['category'], name='outlets_out_categor_0c1a08_idx'),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['is_active'], name='outlets_out_is_acti_33d6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['latitude', 'longitude'], name='outlets_out_latitud_6a2980_idx'),
        ),
        migrations.AddIndex(
            model_name='legacynotice',
            index=models.Index(fields=['outlet'], name='outlets_leg_outlet__0614d5_idx'),
        ),
        migrations.AddIndex(
            model_name='legacynotice',
            index=models.Index(fields=['notice_type'], name='outlets_leg_notice__60826c_idx'),
        ),
        migrations.AddIndex(
            model_name='legacynotice',
            index=models.Index(fields=['issued_date'], name='outlets_leg_issued__ad1ce7_idx'),
        ),
    ]
